### ISSUE TITLE
Performance measurements

### ISSUE THREAD

**Issue by mohanr** [SyntheticSemantics/ClusterSync-Vs-Async-Benchmark#1]
I have a few doubts.

Why haven't you quantified the data based on USL models and other such statistical and queueing models ?
Don't Error bars denote the error in measurements ?
Why do you show 101% of some measurements ?

**Comment by mogill** [comment]
The diagrams indicate the minimum and maximum time measured for a single operation, and the arithmetic mean time over all operations.  The 101% referred to in the header of the example is to offset used to the top of the block illustrating the mean time 1% higher from the bottom of the block.  If the block is 0 height it is not displayed, the offset guarantees a non-zero block height.

**Comment by mohanr** [comment]
I didn't understand the part related to 101%. The graph image link is
broken. Couldn't you use nanoseconds to get a better idea ?
I meant that standard error is used to draw error bars. Right ?

Which set of measurements are for cluster ? Which are for asynch ?

Thanks,
Mohan

**Comment by mogill** [comment]
I fixed the image link so maybe things will become more clear.  I used a [Candlestick Chart](http://en.wikipedia.org/wiki/Candlestick_chart) which requires two ranges, however, my experiments have a min-max range and the other value is a scalar value.  In order for the chart to display the scalar value I must turn it into a range, thus the block ranges from 100-101% of average, solely to make it drawable.

If you take that CSV file and load it into a spreadsheet like Excel or Google Sheets you can change the 101% value to be the same as the 100% value and you'll see the solid block (indicating the average time) disappears from the chart.  The left average column is 100% of average, that is, it is the computed average.  The column to the right of it is 101% of the actual average.
